# Generated by Django 4.1.2 on 2022-12-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_profile_nickname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="nickname", new_name="name",
        ),
    ]
