# Generated by Django 4.1.2 on 2022-12-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_rename_nickname_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.CharField(default="", max_length=140),
        ),
        migrations.AlterField(
            model_name="profile",
            name="iconid",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
